name: "Docker Build Common Action"

description: "This action wraps up the "

inputs:
  context:
    description: "The path to the Dockerfile to build"
    default: "."
    required: false
  gh_token:
    description: "The GitHub Token, value of `secrets.GITHUB_TOKEN` in the calling workflow"
    required: true
  img_name:
    description: "The image name to build"
    required: true
  registry:
    description: "The registry name"
    default: "ghcr.io/croesusfin/"
    required: true


runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2

#    - name: Setup Docker Buildx
#      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.gh_token }}

    - name: Docker meta
      uses: docker/metadata-action@v3
      id: meta
      with:
        images: croesusfin/${{ inputs.img_name }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    # TODO Check the values of arguments passed here
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-${{ inputs.img_name }}
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker Buildx and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: ${{  github.event_name != 'pull_request' }}
        cache-from: type=local,src=/tmp/.buildx-cache-${{ inputs.img_name }}
        cache-to: type=local,dest=/tmp/.buildx-cache-${{ inputs.img_name }}-new
        build-args: 'registry=${{ inputs.registry }}'
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}

    # This bit is necessary if you don't want your cache to grow forever
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache-${{ inputs.img_name }}
        mv /tmp/.buildx-cache-${{ inputs.img_name }}-new /tmp/.buildx-cache-${{ inputs.img_name }}
