name: "Docker Build Common Action"

description: "This action wraps up the "

inputs:
  context:
    description: "The path to the Dockerfile to build"
    default: "."
    required: false
  gh_token:
    description: "The GitHub Token, value of `secrets.GITHUB_TOKEN` in the calling workflow"
    required: true
  img_name:
    description: "The image name to build"
    required: true
  registry:
    description: "The registry name"
    default: "ghcr.io/croesusfin/"
    required: false


runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ inputs.gh_token }}
        registry: ghcr.io

    - name: Docker meta
      uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ inputs.registry }}${{ inputs.img_name }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Docker Buildx and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: ${{  github.event_name != 'pull_request' }}
        cache-from: type=registry,ref=${{ inputs.registry }}${{ inputs.img_name }}:latest
        cache-to: type=inline
        build-args: 'registry=${{ inputs.registry }}'
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
